# Generated by Django 4.2.11 on 2025-03-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoursCalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='HoursSheets',
            field=models.ManyToManyField(to='HoursCalc.hourssheets'),
        ),
    ]
