# Generated by Django 4.2.11 on 2025-03-31 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoursCalc', '0002_member_hourssheets'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SiteName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='Password',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='member',
            name='Username',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('StartTime', models.TimeField()),
                ('EndTime', models.TimeField()),
                ('BreakTime', models.TimeField()),
                ('TotalHours', models.IntegerField()),
                ('JobName', models.ManyToManyField(to='HoursCalc.jobsites')),
            ],
        ),
        migrations.AddField(
            model_name='hourssheets',
            name='Days',
            field=models.ManyToManyField(to='HoursCalc.day'),
        ),
        migrations.AddField(
            model_name='member',
            name='Jobnames',
            field=models.ManyToManyField(to='HoursCalc.jobsites'),
        ),
    ]
